### ISSUE TITLE
nagios_graphite should exit unknown instead of critical  on graphite timeout.

### ISSUE THREAD

**Issue by fessyfoo** [SegFaultAX/nagios_graphite#2]
nagios_graphite  appears to exit 2 critical when graphite times out.   this would result in a page  to users who are invested in the metric but not responsible for the graphite service running.   

Ideally nagios_graphite would exist unknown on graphite timeout.

**Comment by SegFaultAX** [comment]
@fessyfoo Thanks for the report, I'll look into it ASAP.

**Comment by fessyfoo** [comment]
this was the output: `Execution timed out`

**Comment by jknight12882** [comment]
👍

**Comment by SegFaultAX** [comment]
@fessyfoo @jknight12882 The newest version of nagios_graphite, namely [v0.5.0](https://github.com/SegFaultAX/nagios_graphite/tree/v0.5.0) addresses this issue by adding `--http-timeout/-o` for setting an HTTP request timeout which defaults to 10s. Please give that a try and let me know if it resolves the issue for you.

**Comment by fessyfoo** [comment]
fix seems to work well.  thanks!
